spring.application.name=QuizService





spring.datasource.url=jdbc:mysql://localhost:3306/edupulse_db
spring.datasource.username=root
spring.datasource.password=Bavi@2005@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.security.enabled=false
spring.jpa.hibernate.ddl-auto=update
USER_SERVICE_URL=http://localhost:8080/api/users
CLASS_SERVICE_URL=http://localhost:8081/api/classes



server.port=8083
logging.level.org.springframework.cloud.openfeign=DEBUG

